# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cameron Baron - programmer
email: info@cameronbaron.com
description: > # this means to ignore newlines until "baseurl:"
  Home of Cameron from Melb Australia, ex-car and truck spare parts interpreter now posing as
  as a programmer and loving every second of it. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cameronbaron.com" # the base hostname & protocol for your site
twitter_username: Bamran86
github_username:  CameronBaron
youtube_username:
linkedin_username:

# Build settings
markdown: kramdown
permalink: pretty
